#!/usr/bin/env bash
#
# Run Yasuho with an auto-restart loop. Uses the virtualenv created by ./setup.sh,
# falling back to the system python if no venv is present.
#
# Auto-update: before each start the script can pull the latest version from the
# git remote. It ONLY ever fast-forwards a clean, non-diverged checkout, so it can
# never clobber local changes or your gitignored config (bot.ini / tokens.ini).
# Toggle it with the AUTO_UPDATE variable below, or per-run: AUTO_UPDATE=0 ./run.sh
#
# Dependency sync: right after self_update, on every loop iteration, the venv is
# brought up to date with requirements.lock + requirements.txt - whatever code
# ended up checked out, however it got there (fast-forward above, a manual pull,
# a fresh clone). A fingerprint of both files is compared against a stamp inside
# the venv, so a venv already in sync costs zero pip calls, even on a tight
# crash-restart loop. Toggle it with SYNC_DEPS, or per-run: SYNC_DEPS=0 ./run.sh
#
# Secrets live in files this script touches: keep everything owner-only.
umask 077

cd "$(dirname "$0")"

AUTO_UPDATE="${AUTO_UPDATE:-1}"
SYNC_DEPS="${SYNC_DEPS:-1}"

if [ -x ./.venv/bin/python ]; then
    PY=./.venv/bin/python
else
    PY="$(command -v python3.11 || command -v python3.10 || command -v python3)"
    echo "[run] No .venv found - using $PY (run ./setup.sh to create one)."
fi

# --- Out-of-repo backup of the gitignored secrets -----------------------------
# `git clean -fdx` and stray rm's can wipe config/bot.ini, config/tokens.ini and
# config/backup.key (all gitignored, so NOT recoverable from git). Keep a copy
# OUTSIDE the repo and restore it automatically if the working copy goes missing.
#
# backup.key is the one that bites hardest: it decrypts every dump in backups/,
# so losing it with the checkout turns the whole backup set into noise in
# precisely the situation backups exist for.
CONFIG_BACKUP="${YASUHO_CONFIG_BACKUP:-$HOME/.yasuho-config-backup}"

restore_config() {
    for f in bot.ini tokens.ini backup.key; do
        if [ ! -f "config/$f" ] && [ -f "$CONFIG_BACKUP/$f" ]; then
            mkdir -p config
            cp -f "$CONFIG_BACKUP/$f" "config/$f"
            chmod 600 "config/$f" 2>/dev/null
            echo "[run] Restored config/$f from $CONFIG_BACKUP."
        fi
    done
}

backup_config() {
    mkdir -p "$CONFIG_BACKUP" && chmod 700 "$CONFIG_BACKUP" 2>/dev/null
    # The backup key is generated by the bot itself on its first dump - i.e.
    # AFTER this script has started - which is why this runs on every (re)start
    # rather than once. It is never a placeholder, so it needs no filled-in
    # check; a key that exists is always worth mirroring.
    if [ -f config/backup.key ]; then
        cp -f config/backup.key "$CONFIG_BACKUP/backup.key" 2>/dev/null
        chmod 600 "$CONFIG_BACKUP/backup.key" 2>/dev/null
    fi
    # Only snapshot a filled-in config (never a placeholder template) so a
    # broken config can never overwrite a good backup.
    [ -f config/bot.ini ] || return 0
    grep -q 'YOUR_BOT_TOKEN' config/bot.ini && return 0
    cp -f config/bot.ini "$CONFIG_BACKUP/bot.ini" 2>/dev/null
    chmod 600 "$CONFIG_BACKUP/bot.ini" 2>/dev/null
    [ -f config/tokens.ini ] && cp -f config/tokens.ini "$CONFIG_BACKUP/tokens.ini" 2>/dev/null
    [ -f "$CONFIG_BACKUP/tokens.ini" ] && chmod 600 "$CONFIG_BACKUP/tokens.ini" 2>/dev/null
}

self_update() {
    [ "$AUTO_UPDATE" = "1" ] || return 0
    command -v git >/dev/null 2>&1 || return 0
    git rev-parse --is-inside-work-tree >/dev/null 2>&1 || return 0

    echo "[run] Checking for updates..."
    if ! git fetch --quiet origin 2>/dev/null; then
        echo "[run] Could not reach the remote - starting with the local version."
        return 0
    fi

    if ! git rev-parse --abbrev-ref --symbolic-full-name '@{u}' >/dev/null 2>&1; then
        echo "[run] No upstream branch - skipping update."
        return 0
    fi

    local local_rev remote_rev base
    local_rev="$(git rev-parse @)"
    remote_rev="$(git rev-parse '@{u}')"
    base="$(git merge-base @ '@{u}')"

    if [ "$local_rev" = "$remote_rev" ]; then
        echo "[run] Already up to date."
        return 0
    fi
    if [ "$local_rev" != "$base" ]; then
        echo "[run] Local branch has diverged from the remote - skipping auto-update."
        return 0
    fi
    if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
        echo "[run] Local changes present - skipping auto-update to avoid conflicts."
        return 0
    fi

    echo "[run] Update available - fast-forwarding..."
    if git merge --ff-only --quiet '@{u}'; then
        echo "[run] Updated to $(git rev-parse --short HEAD)."
    else
        echo "[run] Fast-forward failed - starting with the local version."
    fi
}

# Dependency sync: keep the venv aligned with requirements.lock + requirements.txt.
# Runs on every loop iteration (not just after a self_update fast-forward) so it
# also covers a manual `git pull`, a fresh clone, or the very first start after
# this check shipped - whatever got the current code onto disk. A fingerprint of
# both files (vs. a stamp left inside the venv) makes a venv already in sync cost
# zero pip calls, which matters on a tight crash-restart loop.
sync_deps() {
    [ "$SYNC_DEPS" = "1" ] || return 0
    # Only a real venv gets this treatment; the system-python fallback keeps
    # today's behaviour (no pip calls at all) - we don't want to touch a Python
    # install we don't own.
    [ -x ./.venv/bin/python ] || return 0

    local stamp fingerprint current
    stamp=".venv/.yasuho-deps-stamp"
    fingerprint="$(sha256sum requirements.lock requirements.txt 2>/dev/null | sha256sum | awk '{print $1}')"
    current="$(cat "$stamp" 2>/dev/null)"

    if [ -n "$fingerprint" ] && [ "$fingerprint" = "$current" ]; then
        return 0
    fi

    echo "[run] Dependencies changed - syncing the venv..."
    # Install the lock first (the exact, audited pins), then requirements.txt as
    # a safety net: if the lock is ever stale or misses a new dependency, this
    # still brings the venv inside requirements.txt's bounds, so a forgotten
    # lock regeneration can never crashloop the bot.
    # pip's own upgrade never gates the sync: an old pip still installs fine.
    "$PY" -m pip install -q -U pip || echo "[run] pip self-upgrade failed - continuing."
    local lock_ok=1
    "$PY" -m pip install -q -r requirements.lock || lock_ok=0
    if "$PY" -m pip install -q -r requirements.txt && [ "$lock_ok" = "1" ]; then
        echo "$fingerprint" > "$stamp"
        echo "[run] Dependencies synced."
    elif [ "$lock_ok" = "0" ]; then
        # No stamp: the next start retries. The lock is resolved for CPython
        # 3.13 on Linux, so on another interpreter it can never apply and only
        # requirements.txt's resolution is used.
        echo "[run] Could not apply requirements.lock - running on requirements.txt's resolution (retrying next start)."
    else
        echo "[run] Dependency sync failed - continuing with the installed set."
    fi
}

while true; do
    # Recover the secrets if a clean/rm wiped them, then snapshot them again.
    # This runs on EVERY (re)start rather than once before the loop because
    # config/backup.key does not exist until the bot takes its first dump: a
    # single pre-loop pass would mirror everything except the one file that
    # cannot be regenerated.
    restore_config
    backup_config
    self_update
    sync_deps
    echo "Starting the bot..."
    "$PY" core.py
    EXIT_CODE=$?

    if [ $EXIT_CODE -eq 0 ]; then
        echo "The bot has stopped normally. Exiting."
        break
    fi
    echo "The bot stopped with an error (code $EXIT_CODE). Restarting in 5 seconds..."
    sleep 5
done
