#!/usr/bin/env bash
#
# Run Yasuho with an auto-restart loop. Uses the virtualenv created by ./setup.sh,
# falling back to the system python if no venv is present.
#
# Auto-update: before each start the script can pull the latest version from the
# git remote. It ONLY ever fast-forwards a clean, non-diverged checkout, so it can
# never clobber local changes or your gitignored config (bot.ini / tokens.ini).
# Toggle it with the AUTO_UPDATE variable below, or per-run: AUTO_UPDATE=0 ./run.sh
#
# Dependency sync: right after self_update, on every loop iteration, the venv is
# brought up to date with requirements.lock + requirements.txt - whatever code
# ended up checked out, however it got there (fast-forward above, a manual pull,
# a fresh clone). A fingerprint of both files is compared against a stamp inside
# the venv, so a venv already in sync costs zero pip calls, even on a tight
# crash-restart loop. Toggle it with SYNC_DEPS, or per-run: SYNC_DEPS=0 ./run.sh
#
# Self-restart: self_update can fast-forward THIS FILE onto disk, but bash has
# already parsed the whole while-loop below into memory by the time it runs -
# a running process never picks up a newer run.sh on its own. So right after
# self_update, every loop iteration also compares a fingerprint of run.sh
# itself against the one taken at launch, and re-execs onto the (possibly new)
# file on disk when they differ. NOTE: a run.sh from BEFORE this check shipped
# has none of this logic, so the very first update past this change still
# needs one manual restart to pick it up - every one after that is automatic.
#
# Secrets live in files this script touches: keep everything owner-only.
umask 077

# Resolve an absolute path to this script BEFORE the cd below can move the
# working directory out from under a relative $0. $0 only keeps resolving
# correctly after that cd when its dirname is "." - a bare "run.sh", or
# "./run.sh" (the invocation this project's docs use) - because then the cd
# is a no-op. Any relative $0 with a REAL directory component (e.g.
# "bots/Yasuho/run.sh", or "../run.sh") breaks the moment the cd changes pwd:
# the same relative string would then be resolved against the NEW pwd and
# point somewhere else entirely (or nowhere). An absolute $0 is unaffected
# either way. Anchoring it here, while pwd is still the one $0 was written
# against, makes it correct in every case.
case "$0" in
    /*) SELF="$0" ;;
    *) SELF="$(pwd)/$0" ;;
esac

cd "$(dirname "$0")"

AUTO_UPDATE="${AUTO_UPDATE:-1}"
SYNC_DEPS="${SYNC_DEPS:-1}"

# Fingerprint of run.sh's own content at launch - see the self-restart note
# above. An empty fingerprint (sha256sum missing, or $SELF unreadable) must
# never be treated as "changed": the comparison below only fires when BOTH
# sides are non-empty, so a tool that can't fingerprint at all simply disables
# the self-restart rather than re-execing on every single loop iteration.
SELF_FINGERPRINT_AT_LAUNCH="$(sha256sum "$SELF" 2>/dev/null | awk '{print $1}')"

if [ -x ./.venv/bin/python ]; then
    PY=./.venv/bin/python
else
    PY="$(command -v python3.11 || command -v python3.10 || command -v python3)"
    echo "[run] No .venv found - using $PY (run ./setup.sh to create one)."
fi

# --- Out-of-repo backup of the gitignored secrets -----------------------------
# `git clean -fdx` and stray rm's can wipe config/bot.ini, config/tokens.ini and
# config/backup.key (all gitignored, so NOT recoverable from git). Keep a copy
# OUTSIDE the repo and restore it automatically if the working copy goes missing.
#
# backup.key is the one that bites hardest: it decrypts every dump in backups/,
# so losing it with the checkout turns the whole backup set into noise in
# precisely the situation backups exist for.
CONFIG_BACKUP="${YASUHO_CONFIG_BACKUP:-$HOME/.yasuho-config-backup}"

restore_config() {
    for f in bot.ini tokens.ini backup.key; do
        if [ ! -f "config/$f" ] && [ -f "$CONFIG_BACKUP/$f" ]; then
            mkdir -p config
            cp -f "$CONFIG_BACKUP/$f" "config/$f"
            chmod 600 "config/$f" 2>/dev/null
            echo "[run] Restored config/$f from $CONFIG_BACKUP."
        fi
    done
}

backup_config() {
    mkdir -p "$CONFIG_BACKUP" && chmod 700 "$CONFIG_BACKUP" 2>/dev/null
    # The backup key is generated by the bot itself on its first dump - i.e.
    # AFTER this script has started - which is why this runs on every (re)start
    # rather than once. It is never a placeholder, so it needs no filled-in
    # check; a key that exists is always worth mirroring.
    if [ -f config/backup.key ]; then
        cp -f config/backup.key "$CONFIG_BACKUP/backup.key" 2>/dev/null
        chmod 600 "$CONFIG_BACKUP/backup.key" 2>/dev/null
    fi
    # Only snapshot a filled-in config (never a placeholder template) so a
    # broken config can never overwrite a good backup.
    [ -f config/bot.ini ] || return 0
    grep -q 'YOUR_BOT_TOKEN' config/bot.ini && return 0
    cp -f config/bot.ini "$CONFIG_BACKUP/bot.ini" 2>/dev/null
    chmod 600 "$CONFIG_BACKUP/bot.ini" 2>/dev/null
    [ -f config/tokens.ini ] && cp -f config/tokens.ini "$CONFIG_BACKUP/tokens.ini" 2>/dev/null
    [ -f "$CONFIG_BACKUP/tokens.ini" ] && chmod 600 "$CONFIG_BACKUP/tokens.ini" 2>/dev/null
}

self_update() {
    [ "$AUTO_UPDATE" = "1" ] || return 0
    command -v git >/dev/null 2>&1 || return 0
    git rev-parse --is-inside-work-tree >/dev/null 2>&1 || return 0

    echo "[run] Checking for updates..."
    if ! git fetch --quiet origin 2>/dev/null; then
        echo "[run] Could not reach the remote - starting with the local version."
        return 0
    fi

    if ! git rev-parse --abbrev-ref --symbolic-full-name '@{u}' >/dev/null 2>&1; then
        echo "[run] No upstream branch - skipping update."
        return 0
    fi

    local local_rev remote_rev base
    local_rev="$(git rev-parse @)"
    remote_rev="$(git rev-parse '@{u}')"
    base="$(git merge-base @ '@{u}')"

    if [ "$local_rev" = "$remote_rev" ]; then
        echo "[run] Already up to date."
        return 0
    fi
    if [ "$local_rev" != "$base" ]; then
        echo "[run] Local branch has diverged from the remote - skipping auto-update."
        return 0
    fi
    if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
        echo "[run] Local changes present - skipping auto-update to avoid conflicts."
        return 0
    fi

    echo "[run] Update available - fast-forwarding..."
    if git merge --ff-only --quiet '@{u}'; then
        echo "[run] Updated to $(git rev-parse --short HEAD)."
    else
        echo "[run] Fast-forward failed - starting with the local version."
    fi
}

# Dependency sync: keep the venv aligned with requirements.lock + requirements.txt.
# Runs on every loop iteration (not just after a self_update fast-forward) so it
# also covers a manual `git pull`, a fresh clone, or the very first start after
# this check shipped - whatever got the current code onto disk. A fingerprint of
# both files (vs. a stamp left inside the venv) makes a venv already in sync cost
# zero pip calls, which matters on a tight crash-restart loop.
sync_deps() {
    [ "$SYNC_DEPS" = "1" ] || return 0
    # Only a real venv gets this treatment; the system-python fallback keeps
    # today's behaviour (no pip calls at all) - we don't want to touch a Python
    # install we don't own.
    [ -x ./.venv/bin/python ] || return 0

    local stamp fingerprint current
    stamp=".venv/.yasuho-deps-stamp"
    fingerprint="$(sha256sum requirements.lock requirements.txt 2>/dev/null | sha256sum 2>/dev/null | awk '{print $1}')"

    if [ -z "$fingerprint" ]; then
        # sha256sum missing, or failing on both files (e.g. neither exists) -
        # an empty fingerprint must never be treated as "drifted": that would
        # resync (full pip installs) on EVERY single start instead of once.
        echo "[run] Could not fingerprint requirements.lock/requirements.txt - skipping dependency sync this start."
        return 0
    fi

    current="$(cat "$stamp" 2>/dev/null)"
    if [ "$fingerprint" = "$current" ]; then
        return 0
    fi

    echo "[run] Dependencies changed - syncing the venv..."
    # Install the lock first (the exact, audited pins), then requirements.txt as
    # a safety net: if the lock is ever stale or misses a new dependency, this
    # still brings the venv inside requirements.txt's bounds, so a forgotten
    # lock regeneration can never crashloop the bot.
    # pip's own upgrade never gates the sync: an old pip still installs fine.
    "$PY" -m pip install -q -U pip || echo "[run] pip self-upgrade failed - continuing."
    local lock_ok=1
    "$PY" -m pip install -q -r requirements.lock || lock_ok=0
    if "$PY" -m pip install -q -r requirements.txt && [ "$lock_ok" = "1" ]; then
        if echo "$fingerprint" > "$stamp" 2>/dev/null; then
            echo "[run] Dependencies synced."
        else
            # The install itself worked - only the stamp write failed (e.g. a
            # read-only venv) - so say so distinctly, and let the next start
            # retry (no stamp was written, so it will look like drift again).
            echo "[run] Dependencies installed, but the stamp could not be written - will re-sync next start."
        fi
    elif [ "$lock_ok" = "0" ]; then
        # No stamp: the next start retries. The lock is resolved for CPython
        # 3.13 on Linux, so on another interpreter it can never apply and only
        # requirements.txt's resolution is used.
        echo "[run] Could not apply requirements.lock - running on requirements.txt's resolution (retrying next start)."
    else
        echo "[run] Dependency sync failed - continuing with the installed set."
    fi
}

while true; do
    # Recover the secrets if a clean/rm wiped them, then snapshot them again.
    # This runs on EVERY (re)start rather than once before the loop because
    # config/backup.key does not exist until the bot takes its first dump: a
    # single pre-loop pass would mirror everything except the one file that
    # cannot be regenerated.
    restore_config
    backup_config
    self_update

    # If self_update just fast-forwarded run.sh itself, THIS process is still
    # running the OLD parse of the while-loop - bash parsed it once, at
    # startup, and never re-reads a script file mid-execution. Re-exec onto
    # the current content so the new loop body (and everything in it, e.g. a
    # future sync_deps change) actually takes effect; only once, since the
    # NEW process repeats this same check against ITS OWN launch fingerprint
    # next time around, and only when both sides fingerprinted successfully
    # (an empty value on either side means "cannot tell" - never "changed").
    self_fingerprint_now="$(sha256sum "$SELF" 2>/dev/null | awk '{print $1}')"
    if [ -n "$SELF_FINGERPRINT_AT_LAUNCH" ] && [ -n "$self_fingerprint_now" ] \
        && [ "$self_fingerprint_now" != "$SELF_FINGERPRINT_AT_LAUNCH" ]; then
        echo "[run] run.sh itself was updated - restarting the script..."
        exec bash "$SELF" "$@"
    fi

    sync_deps
    echo "Starting the bot..."
    "$PY" core.py
    EXIT_CODE=$?

    if [ $EXIT_CODE -eq 0 ]; then
        echo "The bot has stopped normally. Exiting."
        break
    fi
    echo "The bot stopped with an error (code $EXIT_CODE). Restarting in 5 seconds..."
    sleep 5
done
