"""Postgres backups for Yasuho: pg_dump on startup and on demand.

There is no cron/systemd on the host (the run model is ./run.sh in a terminal),
so backups are taken by the bot itself: one fire-and-forget dump at startup
(scheduled from core.py, never blocking readiness) and one on demand via the
owner-only ?backup command. Both go through run_backup below.

Design notes:

- The DSN carries the database password. It is NEVER placed on a subprocess
  command line (ps would expose it) and NEVER logged or echoed. We split the DSN
  into safe non-secret args (host/port/user/dbname on argv) and pass ONLY the
  password through the ``PGPASSWORD`` environment variable, which libpq reads
  natively. argv therefore never contains the secret; ``ps`` is clean. (Passing
  the whole URI on argv would leak it; pg_dump cannot read a value from a named
  env var, so PGPASSWORD is the clean channel for just the secret.)

- The dump is ENCRYPTED AT REST. pg_dump writes to stdout, which is piped
  straight into a symmetric encryption tool; the plaintext dump never touches
  the disk at any point. See the ENCRYPTION section below.

- The encrypted dump is written to ``<name>.part`` and atomically renamed to
  ``<name>`` only after a clean exit of BOTH pipeline stages + fsync, so a
  crashed or killed dump never leaves a file that looks like a valid backup.
  Rotation only ever sees complete dumps.

- Custom format (``-Fc``): compressed, and restorable selectively with
  pg_restore. See the RESTORE section below for the exact procedure.

Everything above run_backup is pure and unit-tested (filename, rotation,
DSN parsing with password redaction, encryptor selection and argv shapes).
run_backup and verify_backup are the async subprocess seams.


ENCRYPTION AT REST
------------------
A dump is the entire database in the clear: every message, token ciphertext and
user record. Sitting unencrypted in backups/ it is the softest target on the
host, so every dump is encrypted as it is produced.

- TOOL. ``gpg --symmetric`` (AES256) is preferred; ``openssl enc -aes-256-cbc
  -pbkdf2`` is the fallback when gpg is absent. Whichever is found first is
  used, and the filename suffix records it (``.dump.gpg`` / ``.dump.enc``) so a
  dump is always verified and decrypted with the tool that made it. If NEITHER
  binary exists the backup FAILS LOUDLY (``BACKUP-NOCRYPT`` in the logs). There
  is deliberately no plaintext fallback: a silent downgrade to plaintext is the
  exact failure this feature exists to prevent.

- KEY. A passphrase generated on first use into ``config/backup.key`` (0600,
  ``secrets.token_urlsafe``), gitignored like the rest of config/. Both tools
  read it with a *file* argument, so the passphrase itself is never on argv and
  ps stays clean. Both read only the FIRST LINE of that file, which is why the
  key is written without a trailing newline.

  BACK THAT FILE UP OUT OF BAND. It is the only thing that can decrypt these
  dumps; losing it turns every backup into noise - and losing it is exactly
  what a ``git clean -fdx`` or a rebuilt disk does, since it is gitignored.
  Creation is logged once at WARNING (``BACKUP-KEY-CREATED``) precisely so that
  never passes unnoticed.

  run.sh and setup.sh therefore mirror it to ``~/.yasuho-config-backup``
  alongside bot.ini/tokens.ini and restore it from there when config/ is
  missing, the same lifeline those secrets already had. That copy is on the
  SAME HOST, so it survives a wiped checkout, not a dead disk: keep your own
  copy somewhere else too. run.sh re-mirrors on every (re)start because the key
  is generated by the bot at its first backup, i.e. after run.sh has started.

- PLAINTEXT DUMPS ALREADY ON DISK from before this change are left exactly
  where they are: they are still recognised by rotation (so they age out
  naturally within BACKUP_KEEP) and still verifiable (verify_backup falls back
  to a direct pg_restore --list for a bare ``.dump``). Nothing re-encrypts them
  in place; delete them by hand if you want them gone sooner.


RESTORE PROCEDURE (manual, deliberate - there is intentionally NO restore code)
------------------------------------------------------------------------------
A restore overwrites live data, so it is always a human act. Do this by hand:

1. STOP THE BOT FIRST. A running bot holds connections and will keep writing;
   restoring under it corrupts the result. Quit ./run.sh (Ctrl-C) and confirm
   the process is gone before touching the database.

2. Pick the dump you want from backups/ (they are named by UTC timestamp,
   newest last alphabetically):

       ls -1 backups/yasuho-*.dump.gpg

3. DECRYPT it to a working file (this is the one-liner; it is byte-identical to
   what pg_dump produced):

       gpg --batch --quiet --no-symkey-cache --pinentry-mode loopback \
           --passphrase-file config/backup.key \
           --output /tmp/yasuho-restore.dump \
           --decrypt backups/yasuho-YYYYMMDD-HHMMSS.dump.gpg

   For a ``.dump.enc`` file (openssl fallback host) the equivalent is:

       openssl enc -d -aes-256-cbc -pbkdf2 -pass file:config/backup.key \
           -in backups/yasuho-YYYYMMDD-HHMMSS.dump.enc \
           -out /tmp/yasuho-restore.dump

   A non-zero exit here means the file is truncated, corrupt, or the key does
   not match it - stop and pick another dump rather than restoring a partial
   one. Shred the decrypted file when you are done (``shred -u``).

4. Restore into the EXISTING database, replacing objects as it goes:

       PGPASSWORD='<password>' pg_restore \
           --host=localhost --port=5432 --username=yasuho \
           --dbname=yasuho_db --clean --if-exists --no-owner \
           /tmp/yasuho-restore.dump

   --clean --if-exists drops each object before recreating it (the drop/recreate
   caveat: this DESTROYS current table contents as it restores; that is the
   point of a restore, but there is no undo). --no-owner keeps ownership as the
   restoring role rather than failing on a missing original role.

   Never put the password on the pg_restore command line as an argument; keep it
   in PGPASSWORD as shown so ps does not expose it.

5. For a from-scratch rebuild instead (database dropped/recreated), create an
   empty yasuho_db first, then run the same command WITHOUT --clean --if-exists.

6. Restart the bot (./run.sh). Startup will take a fresh backup as usual.

   (A pre-encryption ``.dump`` file has no step 3: hand it to pg_restore as-is.)
"""

from __future__ import annotations

import asyncio
import logging
import os
import secrets
import shutil
import signal
import tempfile
from dataclasses import dataclass
from datetime import datetime, timedelta
from urllib.parse import unquote, urlsplit

log = logging.getLogger(__name__)

# How many dumps to keep. At ~one dump per restart plus one per manual ?backup,
# 14 is a comfortable trailing window without unbounded growth (see SCALE STORY
# in the PR notes). Tunable here; the command and startup path both honour it.
BACKUP_KEEP = 14

# Timestamp shape embedded in the filename, e.g. yasuho-20260712-134501.dump.gpg.
# UTC, second resolution, lexically sortable so string order == chronological.
_TS_FORMAT = "%Y%m%d-%H%M%S"
_PREFIX = "yasuho-"
_PART_SUFFIX = ".part"

# Suffixes rotation recognises. ".dump" is the pre-encryption legacy shape: it
# stays recognised ON PURPOSE so old plaintext dumps age out through the normal
# rotation window instead of lingering forever as unrecognised foreign files.
GPG_SUFFIX = ".dump.gpg"
OPENSSL_SUFFIX = ".dump.enc"
PLAIN_SUFFIX = ".dump"
_KNOWN_SUFFIXES = (GPG_SUFFIX, OPENSSL_SUFFIX, PLAIN_SUFFIX)

# The generated passphrase file, relative to the repo root. Gitignored.
KEY_FILENAME = "backup.key"
_REPO_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Entropy of a freshly generated passphrase, in bytes before base64 encoding.
_KEY_BYTES = 48

# Below this, an "encrypted dump" cannot be one: both tools emit a header plus
# at least one cipher block, and a real -Fc archive of even an empty database is
# kilobytes. A cheap stat-only floor that catches the truncated-to-nothing case
# before we pay for a decrypt.
_MIN_ENCRYPTED_BYTES = 512


class BackupKeyError(RuntimeError):
    """The backup passphrase file is missing, empty or unusable."""


def default_key_path() -> str:
    """Absolute path of the generated passphrase file (``config/backup.key``)."""
    return os.path.join(_REPO_DIR, "config", KEY_FILENAME)


class Encryptor:
    """A symmetric encrypt/decrypt tool driven by a passphrase FILE.

    Passphrase-by-file (never by argv) is the whole point of this shape: the
    secret stays out of ``ps`` exactly like PGPASSWORD keeps the DSN password
    out of it. Both concrete tools read only the first line of that file.

    Encryption reads plaintext from stdin (so pg_dump can be piped straight in
    and the plaintext never lands on disk) and writes to an explicit output
    path. Decryption is file-to-file, which is what verify_backup needs.
    """

    name: str = ""
    binary: str = ""
    suffix: str = ""

    def encrypt_args(self, key_path: str, out_path: str) -> list[str]:
        raise NotImplementedError

    def decrypt_args(self, key_path: str, in_path: str, out_path: str) -> list[str]:
        raise NotImplementedError

    def available(self) -> bool:
        return shutil.which(self.binary) is not None


class GpgEncryptor(Encryptor):
    """gpg --symmetric with AES256. Preferred: it authenticates (MDC), so a
    truncated or tampered ciphertext fails the decrypt outright.

    --pinentry-mode loopback is required for --passphrase-file to be honoured in
    batch mode on gpg 2.x; --no-symkey-cache keeps the passphrase out of the
    gpg-agent cache afterwards.
    """

    name = "gpg"
    binary = "gpg"
    suffix = GPG_SUFFIX

    _BASE = (
        "--batch",
        "--yes",
        "--quiet",
        "--no-symkey-cache",
        "--pinentry-mode",
        "loopback",
    )

    def encrypt_args(self, key_path: str, out_path: str) -> list[str]:
        return [
            self.binary,
            *self._BASE,
            "--passphrase-file",
            key_path,
            "--symmetric",
            "--cipher-algo",
            "AES256",
            "--output",
            out_path,
        ]

    def decrypt_args(self, key_path: str, in_path: str, out_path: str) -> list[str]:
        return [
            self.binary,
            *self._BASE,
            "--passphrase-file",
            key_path,
            "--output",
            out_path,
            "--decrypt",
            in_path,
        ]


class OpensslEncryptor(Encryptor):
    """openssl enc -aes-256-cbc -pbkdf2, the fallback when gpg is absent.

    Unauthenticated (CBC, no MAC), so it detects truncation only through a bad
    final block - which is why verify_backup always follows the decrypt with a
    pg_restore --list of the recovered archive rather than trusting the exit
    code alone. -pbkdf2 replaces the legacy one-pass MD5 key derivation.
    """

    name = "openssl"
    binary = "openssl"
    suffix = OPENSSL_SUFFIX

    def encrypt_args(self, key_path: str, out_path: str) -> list[str]:
        return [
            self.binary,
            "enc",
            "-aes-256-cbc",
            "-pbkdf2",
            "-salt",
            "-pass",
            f"file:{key_path}",
            "-out",
            out_path,
        ]

    def decrypt_args(self, key_path: str, in_path: str, out_path: str) -> list[str]:
        return [
            self.binary,
            "enc",
            "-d",
            "-aes-256-cbc",
            "-pbkdf2",
            "-pass",
            f"file:{key_path}",
            "-in",
            in_path,
            "-out",
            out_path,
        ]


# Preference order: gpg first (authenticated), openssl as the fallback.
ENCRYPTORS: tuple[Encryptor, ...] = (GpgEncryptor(), OpensslEncryptor())


def resolve_encryptor() -> Encryptor | None:
    """Return the first installed encryptor, or None if the host has neither.

    Deliberately not cached: a backup is rare and shutil.which is cheap, and a
    cache would pin a "no tool" answer for the whole process lifetime.
    """
    for enc in ENCRYPTORS:
        if enc.available():
            return enc
    return None


def encryptor_for(name: str) -> Encryptor | None:
    """Return the encryptor that produced ``name``, by suffix, or None.

    A file must be decrypted with the tool that wrote it, never with whatever
    happens to be installed today, so verification resolves by SUFFIX. None
    means a legacy plaintext ``.dump`` (or a foreign name).
    """
    base = os.path.basename(name)
    for enc in ENCRYPTORS:
        if base.endswith(enc.suffix):
            return enc
    return None


def ensure_key(path: str) -> str:
    """Return ``path``, creating a 0600 passphrase file there if it is missing.

    Creation is O_CREAT|O_EXCL so two concurrent backups can never both write a
    key (the loser simply uses the winner's), and the file is fsynced along with
    its directory before it is handed out: a key that only exists in page cache
    while ciphertext it produced is already durable would be a data-loss bug.

    Two different jobs, do not conflate them: the 0600 passed to os.open covers
    CREATION (a umask can only narrow that mode, never widen it, so a permissive
    umask is harmless), while the chmod that follows covers EVERY call and is
    what clamps an already-existing key a human left group- or world-readable.
    Written WITHOUT a trailing newline - both tools read
    the first line, so a stray newline would be silently stripped anyway, but
    keeping the file exactly one token long avoids any doubt.

    Raises BackupKeyError if the file exists but is empty (encrypting with an
    empty passphrase must never happen silently).
    """
    directory = os.path.dirname(path) or "."
    os.makedirs(directory, exist_ok=True)
    try:
        fd = os.open(path, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
    except FileExistsError:
        pass
    else:
        with os.fdopen(fd, "w") as handle:
            handle.write(secrets.token_urlsafe(_KEY_BYTES))
            handle.flush()
            os.fsync(handle.fileno())
        _fsync_dir(directory)
        log.warning(
            "BACKUP-KEY-CREATED: generated a new backup encryption key at %s - "
            "copy it somewhere safe OUT OF BAND; without it no encrypted dump "
            "can ever be restored.",
            path,
        )
    try:
        os.chmod(path, 0o600)
        with open(path, "rb") as handle:
            first_line = handle.readline().strip()
    except OSError as exc:
        raise BackupKeyError(f"cannot read backup key {path}: {exc}") from exc
    if not first_line:
        raise BackupKeyError(f"backup key {path} is empty")
    return path


def backup_filename(now: datetime, suffix: str = GPG_SUFFIX) -> str:
    """Return the dump filename for ``now`` (naive/aware both fine, read as-is).

    Format: ``yasuho-YYYYMMDD-HHMMSS<suffix>``, where the suffix names the tool
    that encrypted it. The caller decides the timezone; core.py and the command
    both pass ``datetime.utcnow()`` so filenames sort chronologically as plain
    strings (the suffix is constant within a host, so it never perturbs order).
    """
    return f"{_PREFIX}{now.strftime(_TS_FORMAT)}{suffix}"


def _parse_ts(name: str) -> datetime | None:
    """Extract the embedded timestamp from a dump name, or None if it is not one.

    Any of the known suffixes counts, including the legacy plaintext ``.dump``,
    so rotation keeps ordering and ageing out pre-encryption dumps. Foreign
    files (no recognised prefix/suffix, or an unparseable timestamp) return None
    so rotation ignores them rather than deleting them.
    """
    if not name.startswith(_PREFIX):
        return None
    for suffix in _KNOWN_SUFFIXES:
        if name.endswith(suffix):
            core = name[len(_PREFIX) : -len(suffix)]
            break
    else:
        return None
    try:
        return datetime.strptime(core, _TS_FORMAT)
    except ValueError:
        return None


def rotation_victims(existing_names, keep: int = BACKUP_KEEP) -> list[str]:
    """Return the dump names to delete so only the newest ``keep`` remain.

    Only recognised dump names (``yasuho-<ts>`` plus any known suffix, with a
    valid timestamp - so encrypted dumps and the pre-encryption plaintext ones
    share one timeline) are considered; foreign files are ignored and never
    returned, and neither is an in-progress ``.part``. Ordering is by the
    timestamp embedded in the name (not filesystem mtime), so it is deterministic
    and testable. Ties on identical timestamps are broken by name for stability.
    With ``keep`` or fewer real dumps, nothing is deleted.
    """
    if keep < 0:
        keep = 0
    dated = [(ts, name) for name in existing_names if (ts := _parse_ts(name))]
    # Newest first; secondary sort on name keeps duplicate timestamps stable.
    dated.sort(key=lambda item: (item[0], item[1]), reverse=True)
    return [name for _, name in dated[keep:]]


def newest_dump(existing_names) -> tuple[datetime, str] | None:
    """Return ``(timestamp, name)`` of the newest recognised dump, or None.

    Pure counterpart to ``rotation_victims``: it applies the same name parsing
    and the same ordering (embedded timestamp, name as tie-break) but returns
    only the single newest dump. Foreign files are ignored. Returns None when no
    recognised dump is present, which is the caller's cue that no backup exists.
    """
    dated = [(ts, name) for name in existing_names if (ts := _parse_ts(name))]
    if not dated:
        return None
    dated.sort(key=lambda item: (item[0], item[1]))
    return dated[-1]


@dataclass(frozen=True)
class PgConn:
    """Non-secret connection pieces plus the password, with redacted display.

    The password is a plain field but ``repr``/``str`` never reveal it, so a
    PgConn can be logged or dropped into a traceback without leaking the secret.
    Use ``pgpassword`` explicitly (and only) to feed the PGPASSWORD env var.
    """

    host: str | None
    port: str | None
    user: str | None
    dbname: str | None
    password: str | None

    def __repr__(self) -> str:  # never expose the password
        pw = "***" if self.password else None
        return (
            f"PgConn(host={self.host!r}, port={self.port!r}, user={self.user!r}, "
            f"dbname={self.dbname!r}, password={pw!r})"
        )

    __str__ = __repr__

    @property
    def pgpassword(self) -> str | None:
        """The raw password for the PGPASSWORD env var (never for argv/logs)."""
        return self.password

    def dump_args(self) -> list[str]:
        """libpq connection args safe to place on argv (no secret among them)."""
        args: list[str] = []
        if self.host:
            args.append(f"--host={self.host}")
        if self.port:
            args.append(f"--port={self.port}")
        if self.user:
            args.append(f"--username={self.user}")
        if self.dbname:
            args.append(f"--dbname={self.dbname}")
        return args


def parse_dsn(dsn: str) -> PgConn:
    """Split a ``postgresql://`` DSN into a PgConn (password kept, but redacted).

    Percent-encoded userinfo is decoded so the password handed to PGPASSWORD is
    the real one. The leading '/' of the path is the database name. Never logs
    the input.
    """
    parts = urlsplit(dsn)
    dbname = parts.path.lstrip("/") or None
    return PgConn(
        host=parts.hostname,
        port=str(parts.port) if parts.port else None,
        user=unquote(parts.username) if parts.username else None,
        dbname=unquote(dbname) if dbname else None,
        password=unquote(parts.password) if parts.password else None,
    )


@dataclass(frozen=True)
class BackupResult:
    """Outcome of one run_backup call (safe to log/echo - no secrets)."""

    ok: bool
    path: str | None = None
    size: int | None = None
    deleted: int = 0
    error: str | None = None


@dataclass(frozen=True)
class BackupReport:
    """Freshness snapshot of the newest dump on disk (no secrets, safe to log).

    ``timestamp`` is the UTC time embedded in the filename, not filesystem mtime,
    so it is deterministic and matches what rotation orders by. ``age`` derives
    from it against a caller-supplied ``now`` (kept as an argument rather than
    calling utcnow internally so the logic stays pure and unit-testable).
    """

    name: str
    path: str
    timestamp: datetime
    size: int

    def age(self, now: datetime) -> timedelta:
        return now - self.timestamp


def latest_backup_report(backups_dir: str) -> BackupReport | None:
    """Return a BackupReport for the newest dump in ``backups_dir``, or None.

    None means no recognised dump exists (empty/missing directory, or only
    foreign files). The newest dump is selected by the timestamp embedded in the
    filename via ``newest_dump``; size comes from a single stat. Never raises: a
    missing directory or unreadable file degrades to None / size 0.
    """
    try:
        names = os.listdir(backups_dir)
    except OSError:
        return None
    newest = newest_dump(names)
    if newest is None:
        return None
    ts, name = newest
    path = os.path.join(backups_dir, name)
    try:
        size = os.path.getsize(path)
    except OSError:
        size = 0
    return BackupReport(name=name, path=path, timestamp=ts, size=size)


@dataclass(frozen=True)
class VerifyResult:
    """Outcome of a pg_restore --list integrity probe (safe to log, no secrets)."""

    ok: bool
    error: str | None = None


def _map_verify_result(returncode: int, stderr: bytes | None) -> VerifyResult:
    """Map a finished pg_restore --list process to a VerifyResult (pure).

    A zero exit means the archive's table of contents parsed cleanly. Any other
    exit is treated as a corrupt/unreadable dump; the stderr tail is attached
    (trimmed and never carrying a secret - --list opens no database connection).
    """
    if returncode != 0:
        return VerifyResult(
            ok=False,
            error=f"pg_restore --list exit {returncode}: {_stderr_tail(stderr)}",
        )
    return VerifyResult(ok=True)


def _map_decrypt_result(
    binary: str, returncode: int, stderr: bytes | None
) -> VerifyResult:
    """Map a finished decrypt process to a VerifyResult (pure).

    A non-zero exit is the decryptability failure this check exists for: wrong
    or lost key, truncated ciphertext, bit rot. gpg additionally verifies its
    MDC, so for a .dump.gpg this covers the WHOLE file, not just its head.
    """
    if returncode != 0:
        return VerifyResult(
            ok=False,
            error=f"{binary} --decrypt exit {returncode}: {_stderr_tail(stderr)}",
        )
    return VerifyResult(ok=True)


def _check_size_floor(path: str) -> VerifyResult:
    """Cheap stat-only plausibility gate before paying for a decrypt (pure-ish)."""
    try:
        size = os.path.getsize(path)
    except OSError as exc:
        return VerifyResult(ok=False, error=f"cannot stat dump: {exc}")
    if size < _MIN_ENCRYPTED_BYTES:
        return VerifyResult(
            ok=False,
            error=(
                f"encrypted dump is only {size} bytes "
                f"(floor {_MIN_ENCRYPTED_BYTES}) - truncated or empty"
            ),
        )
    return VerifyResult(ok=True)


async def _pg_restore_list(path: str) -> VerifyResult:
    """Run ``pg_restore --list`` on a PLAINTEXT archive. No restore, no database."""
    try:
        proc = await asyncio.create_subprocess_exec(
            "pg_restore",
            "--list",
            path,
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.PIPE,
        )
        _, stderr = await proc.communicate()
    except Exception as exc:  # spawn failure (pg_restore missing, etc.)
        return VerifyResult(ok=False, error=f"pg_restore did not start: {exc}")
    return _map_verify_result(proc.returncode, stderr)


async def verify_backup(path: str, *, key_path: str | None = None) -> VerifyResult:
    """Check a dump's integrity without restoring anything.

    For an ENCRYPTED dump this is two stages, and both must pass:

    1. Decrypt it to a private temp file beside it. This reads the ciphertext
       END TO END, so it catches truncation, bit rot, a wrong/lost key - and
       with gpg the MDC makes it tamper-evident. (The plaintext check it
       replaces could not see any of that.)
    2. ``pg_restore --list`` the recovered archive, which parses the custom-format
       header and TOC without connecting to or writing any database. This is
       byte-for-byte the check that ran before encryption, preserved exactly.

    The temp file is created 0600 by tempfile inside the already-0700 backups
    directory and unlinked in a finally, so a decrypted copy never outlives the
    probe. A decrypt is deliberately NOT piped into pg_restore: --list stops
    reading after the TOC, which would SIGPIPE the decryptor and report a
    perfectly good dump as corrupt (and would leave the tail unchecked).

    A pre-encryption ``.dump`` gets stage 2 only, so old dumps stay verifiable.

    Never raises: every failure path comes back as ``VerifyResult(ok=False,
    error=...)``. No database password is needed or passed; the backup
    passphrase is named by path only. argv and env stay secret-free.
    """
    enc = encryptor_for(path)
    if enc is None:
        return await _pg_restore_list(path)  # legacy plaintext dump

    floor = _check_size_floor(path)
    if not floor.ok:
        return floor
    if not enc.available():
        return VerifyResult(
            ok=False,
            error=f"{enc.binary} is not installed - cannot decrypt this dump",
        )
    key_path = key_path or default_key_path()
    if not os.path.exists(key_path):
        return VerifyResult(
            ok=False, error=f"backup key {key_path} is missing - cannot decrypt"
        )

    directory = os.path.dirname(os.path.abspath(path))
    try:
        handle, plain_path = tempfile.mkstemp(dir=directory, prefix=".verify-")
        os.close(handle)
    except OSError as exc:
        return VerifyResult(ok=False, error=f"cannot stage a decrypt: {exc}")
    try:
        # Both tools refuse to write onto an existing file unless told to; gpg
        # gets --yes from its base flags and openssl overwrites by default, so
        # the mkstemp placeholder is fine as the output path.
        try:
            proc = await asyncio.create_subprocess_exec(
                *enc.decrypt_args(key_path, path, plain_path),
                stdout=asyncio.subprocess.DEVNULL,
                stderr=asyncio.subprocess.PIPE,
            )
            _, stderr = await proc.communicate()
        except Exception as exc:  # spawn failure
            return VerifyResult(ok=False, error=f"{enc.binary} did not start: {exc}")
        decrypted = _map_decrypt_result(enc.binary, proc.returncode, stderr)
        if not decrypted.ok:
            return decrypted
        return await _pg_restore_list(plain_path)
    finally:
        _safe_unlink(plain_path)


def human_size(num: int) -> str:
    """Human-readable byte count, e.g. 12.3 MiB. ASCII only, one decimal place."""
    value = float(num)
    for unit in ("B", "KiB", "MiB", "GiB", "TiB"):
        if value < 1024 or unit == "TiB":
            if unit == "B":
                return f"{int(value)} {unit}"
            return f"{value:.1f} {unit}"
        value /= 1024
    return f"{num} B"  # unreachable; keeps type checkers happy


def _stderr_tail(stderr: bytes | None) -> str:
    """Decode and trim a child's stderr for a log line (bounded, never secret)."""
    return (stderr or b"").decode("utf-8", "replace").strip()[:500]


async def run_backup(
    dsn: str,
    backups_dir: str,
    *,
    keep: int = BACKUP_KEEP,
    key_path: str | None = None,
) -> BackupResult:
    """Take one ENCRYPTED pg_dump (-Fc) into ``backups_dir`` and rotate old dumps.

    The single seam both the startup backup (core.py) and the owner ?backup
    command go through, so there is exactly one place where encryption happens.

    Never raises into the caller: any failure (spawn error, non-zero exit, IO,
    unusable key, no encryption tool) comes back as ``BackupResult(ok=False,
    error=...)`` with a short, secret-free message. On success the ciphertext is
    fsynced and atomically renamed into place, old dumps beyond ``keep`` are
    deleted, and the result carries the path, byte size and delete count.

    Two secrets, two channels, neither on argv: the database password travels
    only through PGPASSWORD, the backup passphrase only through a 0600 file
    named on argv (its path, never its contents). ps stays clean.

    If no encryption tool is installed the backup FAILS - it never degrades to
    writing a plaintext dump - and says so under the greppable BACKUP-NOCRYPT.
    """
    conn = parse_dsn(dsn)

    enc = resolve_encryptor()
    if enc is None:
        tools = ", ".join(e.binary for e in ENCRYPTORS)
        error = (
            f"no symmetric encryption tool found (looked for: {tools}); "
            "refusing to write a plaintext dump"
        )
        log.error("BACKUP-NOCRYPT: %s", error)
        return BackupResult(ok=False, error=error)

    try:
        key_path = ensure_key(key_path or default_key_path())
    except (BackupKeyError, OSError) as exc:
        log.error("BACKUP-KEY: %s", exc)
        return BackupResult(ok=False, error=f"backup key unusable: {exc}")

    try:
        # Dumps hold the full database: keep the directory owner-only.
        os.makedirs(backups_dir, mode=0o700, exist_ok=True)
        os.chmod(backups_dir, 0o700)
    except OSError as exc:
        return BackupResult(ok=False, error=f"cannot create backups dir: {exc}")

    now = datetime.utcnow()
    final_name = backup_filename(now, enc.suffix)
    final_path = os.path.join(backups_dir, final_name)
    part_path = os.path.join(backups_dir, final_name + _PART_SUFFIX)

    # Child env: inherit ours, add PGPASSWORD (the only place the secret lives).
    env = dict(os.environ)
    if conn.pgpassword is not None:
        env["PGPASSWORD"] = conn.pgpassword
    else:
        env.pop("PGPASSWORD", None)

    # -Fc custom format on stdout, piped into the encryptor which writes the
    # .part file. Nothing buffers the dump in memory and, crucially, the
    # plaintext never exists as a file. No password on either argv.
    dump_args = ["pg_dump", "-Fc", *conn.dump_args()]
    enc_args = enc.encrypt_args(key_path, part_path)

    read_fd, write_fd = os.pipe()
    dump_proc = None
    enc_proc = None
    try:
        dump_proc = await asyncio.create_subprocess_exec(
            *dump_args,
            stdout=write_fd,
            stderr=asyncio.subprocess.PIPE,
            env=env,
        )
        # Our copy of the write end must go now, or the encryptor never sees EOF.
        os.close(write_fd)
        write_fd = -1
        enc_proc = await asyncio.create_subprocess_exec(
            *enc_args,
            stdin=read_fd,
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.PIPE,
        )
        os.close(read_fd)
        read_fd = -1
    except Exception as exc:  # spawn failure (pg_dump or the tool missing, ...)
        for fd in (read_fd, write_fd):
            if fd != -1:
                os.close(fd)
        if dump_proc is not None:
            # pg_dump is now writing into a pipe nobody reads; do not leave it.
            try:
                dump_proc.kill()
            except ProcessLookupError:
                pass
            await dump_proc.wait()
        _safe_unlink(part_path)
        return BackupResult(ok=False, error=f"backup pipeline did not start: {exc}")

    # Drain both stderr pipes concurrently: waiting on one at a time would
    # deadlock if the other filled its pipe buffer.
    (_, dump_err), (_, enc_err) = await asyncio.gather(
        dump_proc.communicate(), enc_proc.communicate()
    )

    # FAILURE ATTRIBUTION. pg_dump normally goes first: if the dump itself
    # failed, the encryptor's complaint is just fallout. SIGPIPE is the one
    # inversion. An encryptor that dies mid-stream (disk full, crash, OOM) drops
    # the read end of the pipe, so the kernel kills pg_dump with SIGPIPE and it
    # reports exit -13 with empty stderr. Blaming pg_dump for that would hide
    # the real cause behind an empty message AND skip the greppable
    # BACKUP-NOCRYPT marker this module documents - and whether the encryptor
    # drained stdin before dying depends on the dump's size, so the same fault
    # would look nondeterministic in the field. When pg_dump died of SIGPIPE and
    # the encryptor also failed, the encryptor is the cause.
    #
    # stderr may name host/user/db but never the password (it is not on argv and
    # pg_dump does not echo PGPASSWORD). Trim to keep logs bounded.
    encryptor_failed = enc_proc.returncode != 0
    dump_died_of_sigpipe = dump_proc.returncode == -signal.SIGPIPE
    if dump_proc.returncode != 0 and not (dump_died_of_sigpipe and encryptor_failed):
        _safe_unlink(part_path)
        return BackupResult(
            ok=False,
            error=f"pg_dump exit {dump_proc.returncode}: {_stderr_tail(dump_err)}",
        )
    if encryptor_failed:
        _safe_unlink(part_path)
        error = f"{enc.binary} exit {enc_proc.returncode}: {_stderr_tail(enc_err)}"
        if dump_died_of_sigpipe:
            error += " (it died mid-stream; pg_dump was then killed by SIGPIPE)"
        log.error("BACKUP-NOCRYPT: encryption failed, no dump written: %s", error)
        return BackupResult(ok=False, error=error)

    # Durability: fsync the finished .part, then atomically rename into place so
    # a crash between here and there can never expose a half-written dump.
    try:
        # The encryptor created the file under the process umask; it holds the
        # whole database, so clamp it owner-only before it becomes visible.
        os.chmod(part_path, 0o600)
        _fsync_file(part_path)
        os.replace(part_path, final_path)
        _fsync_dir(backups_dir)
        size = os.path.getsize(final_path)
    except OSError as exc:
        _safe_unlink(part_path)
        return BackupResult(ok=False, error=f"finalising dump failed: {exc}")

    # Rotation is best-effort: a delete failure must not fail an otherwise good
    # backup, so we count what we managed to remove and log the rest.
    deleted = 0
    try:
        names = os.listdir(backups_dir)
    except OSError:
        names = []
    for victim in rotation_victims(names, keep=keep):
        if _safe_unlink(os.path.join(backups_dir, victim)):
            deleted += 1

    return BackupResult(ok=True, path=final_path, size=size, deleted=deleted)


def _fsync_file(path: str) -> None:
    fd = os.open(path, os.O_RDONLY)
    try:
        os.fsync(fd)
    finally:
        os.close(fd)


def _fsync_dir(path: str) -> None:
    """fsync the directory so the rename itself is durable. Best-effort."""
    try:
        fd = os.open(path, os.O_RDONLY)
    except OSError:
        return
    try:
        os.fsync(fd)
    except OSError:
        pass
    finally:
        os.close(fd)


def _safe_unlink(path: str) -> bool:
    try:
        os.unlink(path)
        return True
    except FileNotFoundError:
        return False
    except OSError as exc:
        log.warning("backup: could not delete %s (%s)", os.path.basename(path), exc)
        return False
